name: 'Setup Go and Run Commands'
description: 'Sets up a Go environment and runs specified bash commands'
author: 'Your Name <your.email@example.com>'
inputs:
  json-value:
    description: 'Json Value'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.0
      
    - name: Run Custom Commands
      run: |
        if [ -z ${{ inputs.json-value }} ]; then
          echo "Json value is populated"
        else
          echo "Json value is empty"
        fi
      shell: bash
