name: Ingest JSON input and mask
# This workflow is to ingest a json input and mask the value 
# before being used in an action to validate the contents.

# test.json in the repo contains the json I was passing into
# the workflow run as I was testing.

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - id: generate-output
        name: Generate output
        run: |
          echo "TEST_OUTPUT=$(cat nofile.txt)" >> $GITHUB_OUTPUT

      - name: Check output from previous step
        run: |
          echo "{{ steps.generate-output.outputs.TEST_OUTPUT }}"
