name: Test Workflow

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - id: generate-output
        name: Generate output
        run: |
          cat $GITHUB_EVENT_PATH
          gh run --repo ${{ github.repository }} view ${{ github.run_id }} --json jobs --jq '.jobs[]'
      #     OUTPUT=$(cat nofile.txt 2>&1) || true
      #     echo "TEST_OUTPUT=$OUTPUT" >> $GITHUB_OUTPUT

      # - name: Check output from previous step
      #   run: |
      #     NEW_VAR=${{ steps.generate-output.outputs.TEST_OUTPUT }}
      #     echo "${{ steps.generate-output.outputs.TEST_OUTPUT }}"
