name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - id: generate-output
        name: Generate output
        run: |
          echo "TEST_OUTPUT=$(cat nofile.txt; exit 254 2>&1)" >> $GITHUB_OUTPUT

      - name: Check output from previous step
        run: |
          NEW_VAR=${{ steps.generate-output.outputs.TEST_OUTPUT }}
          echo "${{ steps.generate-output.outputs.TEST_OUTPUT }}"
