on:
  workflow_dispatch:
    inputs:
      string:
        description: 'Input test string'
        required: false
        type: string
      json:
        description: 'Input test json'
        required: true
        type: string

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set and mask variable
        run: |
          JSON_TEST=$(jq -r '.inputs.json' $GITHUB_EVENT_PATH)
          echo "JSON_TEST=$JSON_TEST" >> $GITHUB_ENV
          JSON_VALUE=$(echo "$JSON_TEST" | jq -r '.test')
          echo "Json value before adding mask: $JSON_VALUE"
          echo "::add-mask::$JSON_VALUE"
          echo "Json value after adding mask: $JSON_VALUE"
          echo ${{ env.JSON_VALUE }}

    #   - name: Call go action
    #     uses: lkoopz/test-workflows@main
    #     with:
    #       json-value: ${{ env.JSON_VALUE }}
        



# TO DO
#  call an action passing the masked var
#  have the action
#    setup go
#    run a go script using the masked var
