name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - id: generate-output
        name: Generate output
        run: |
          OUTPUT=$(cat nofile.txt 2>&1) || true
          echo "TEST_OUTPUT=$OUTPUT" >> $GITHUB_ENV

      - name: Check output from previous step
        run: |
          NEW_VAR=${{ steps.generate-output.outputs.TEST_OUTPUT }}
          echo "${{ steps.generate-output.outputs.TEST_OUTPUT }}"
